//
//  Countries.swift
//  LeadLinkApp
//
//  Created by Marko Dimitrijevic on 06/06/2019.
//  Copyright © 2019 Marko Dimitrijevic. All rights reserved.
//

import Foundation

struct CountriesManager {
    var countries = [String: String]()
    init() {
        countries = countriesDict
    }
    
    private let countriesDict = [
        "1":"AFGHANISTAN",
        "2":"ALAND ISLANDS",
        "3":"ALBANIA",
        "4":"ALGERIA",
        "5":"AMERICAN SAMOA",
        "6":"ANDORRA",
        "7":"ANGOLA",
        "8":"ANGUILLA",
        "9":"ANTARCTICA",
        "10":"ANTIGUA AND BARBUDA",
        "11":"ARGENTINA",
        "12":"ARMENIA",
        "13":"ARUBA",
        "14":"AUSTRALIA",
        "15":"AUSTRIA",
        "16":"AZERBAIJAN",
        "17":"BAHAMAS",
        "18":"BAHRAIN",
        "19":"BANGLADESH",
        "20":"BARBADOS",
        "21":"BELARUS",
        "22":"BELGIUM",
        "23":"BELIZE",
        "24":"BENIN",
        "25":"BERMUDA",
        "26":"BHUTAN",
        "27":"BOLIVIA",
        "28":"BONAIRE, SINT EUSTATIUS AND SABA",
        "29":"BOSNIA AND HERZEGOVINA",
        "30":"BOTSWANA",
        "31":"BOUVET ISLAND (BOUVETOYA)",
        "32":"BRAZIL",
        "33":"BRITISH INDIAN OCEAN TERRITORY (CHAGOS ARCHIPELAGO)",
        "34":"BRITISH VIRGIN ISLANDS",
        "35":"BRUNEI DARUSSALAM",
        "36":"BULGARIA",
        "37":"BURKINA FASO",
        "38":"BURUNDI",
        "39":"CAMBODIA",
        "40":"CAMEROON",
        "41":"CANADA",
        "42":"CAPE VERDE",
        "43":"CAYMAN ISLANDS",
        "44":"CENTRAL AFRICAN REPUBLIC",
        "45":"CHAD",
        "46":"CHILE",
        "47":"CHINA",
        "48":"CHRISTMAS ISLAND",
        "49":"COCOS (KEELING) ISLANDS",
        "50":"COLOMBIA",
        "51":"COMOROS",
        "52":"CONGO THE DEMOCRATIC REPUBLIC OF THE",
        "53":"CONGO",
        "54":"COOK ISLANDS",
        "55":"COSTA RICA",
        "56":"CROATIA",
        "57":"CUBA",
        "58":"CURACAO",
        "59":"CYPRUS",
        "60":"CZECH REPUBLIC",
        "61":"DENMARK",
        "62":"DJIBOUTI",
        "63":"DOMINICA",
        "64":"DOMINICAN REPUBLIC",
        "65":"ECUADOR",
        "66":"EGYPT",
        "67":"EL SALVADOR",
        "68":"EQUATORIAL GUINEA",
        "69":"ERITREA",
        "70":"ESTONIA",
        "71":"ETHIOPIA",
        "72":"FALKLAND ISLANDS (MALVINAS)",
        "73":"FAROE ISLANDS",
        "74":"FIJI",
        "75":"FINLAND",
        "76":"FRANCE",
        "77":"FRENCH GUIANA",
        "78":"FRENCH POLYNESIA",
        "79":"FRENCH SOUTHERN TERRITORIES",
        "80":"GABON",
        "81":"GAMBIA",
        "82":"GEORGIA",
        "83":"GERMANY",
        "84":"GHANA",
        "85":"GIBRALTAR",
        "86":"GREECE",
        "87":"GREENLAND",
        "88":"GRENADA",
        "89":"GUADELOUPE",
        "90":"GUAM",
        "91":"GUATEMALA",
        "92":"GUERNSEY",
        "93":"GUINEA",
        "94":"GUINEA-BISSAU",
        "95":"GUYANA",
        "96":"HAITI",
        "97":"HEARD ISLAND AND MCDONALD ISLANDS",
        "98":"HOLY SEE (VATICAN CITY STATE)",
        "99":"HONDURAS",
        "100":"HONG KONG, P.R. CHINA",
        "101":"HUNGARY",
        "102":"ICELAND",
        "103":"INDIA",
        "104":"INDONESIA",
        "105":"IRAN",
        "106":"IRAQ",
        "107":"IRELAND",
        "108":"ISLE OF MAN",
        "109":"ISRAEL",
        "110":"ITALY",
        "111":"IVORY COAST",
        "112":"JAMAICA",
        "113":"JAPAN",
        "114":"JERSEY",
        "115":"JORDAN",
        "116":"KAZAKHSTAN",
        "117":"KENYA",
        "118":"KIRIBATI",
        "119":"KOSOVO*",
        "120":"KUWAIT",
        "121":"KYRGYZ REPUBLIC",
        "122":"LAOS",
        "123":"LATVIA",
        "124":"LEBANON",
        "125":"LESOTHO",
        "126":"LIBERIA",
        "127":"LIBYA",
        "128":"LIECHTENSTEIN",
        "129":"LITHUANIA",
        "130":"LUXEMBOURG",
        "131":"MACAO",
        "132":"REPUBLIC OF NORTH MACEDONIA",
        "133":"MADAGASCAR",
        "134":"MALAWI",
        "135":"MALAYSIA",
        "136":"MALDIVES",
        "137":"MALI",
        "138":"MALTA",
        "139":"MARSHALL ISLANDS",
        "140":"MARTINIQUE",
        "141":"MAURITANIA",
        "142":"MAURITIUS",
        "143":"MAYOTTE",
        "144":"MEXICO",
        "145":"MICRONESIA",
        "146":"MOLDOVA",
        "147":"MONACO",
        "148":"MONGOLIA",
        "149":"MONTENEGRO",
        "150":"MONTSERRAT",
        "151":"MOROCCO",
        "152":"MOZAMBIQUE",
        "153":"MYANMAR",
        "154":"NAMIBIA",
        "155":"NAURU",
        "156":"NEPAL",
        "157":"NETHERLANDS",
        "158":"NEW CALEDONIA",
        "159":"NEW ZEALAND",
        "160":"NICARAGUA",
        "161":"NIGER",
        "162":"NIGERIA",
        "163":"NIUE",
        "164":"NORFOLK ISLAND",
        "165":"NORTH KOREA",
        "166":"NORTHERN MARIANA ISLANDS",
        "167":"NORWAY",
        "168":"OMAN",
        "169":"PAKISTAN",
        "170":"PALAU",
        "171":"PALESTINE",
        "172":"PANAMA",
        "173":"PAPUA NEW GUINEA",
        "174":"PARAGUAY",
        "175":"PERU",
        "176":"PHILIPPINES",
        "177":"PITCAIRN ISLANDS",
        "178":"POLAND",
        "179":"PORTUGAL",
        "180":"PUERTO RICO",
        "181":"QATAR",
        "182":"REUNION",
        "183":"ROMANIA",
        "184":"RUSSIA",
        "185":"RWANDA",
        "186":"SAINT BARTHOLEMY",
        "187":"SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
        "188":"SAINT KITTS AND NEVIS",
        "189":"SAINT LUCIA",
        "190":"SAINT MARTIN",
        "191":"SAINT PIERRE AND MIQUELON",
        "192":"SAINT VINCENT AND THE GRENADINES",
        "193":"SAMOA",
        "194":"SAN MARINO",
        "195":"SAO TOME AND PRINCIPE",
        "196":"SAUDI ARABIA",
        "197":"SENEGAL",
        "198":"SERBIA",
        "199":"SEYCHELLES",
        "200":"SIERRA LEONE",
        "201":"SINGAPORE",
        "202":"SINT MAARTEN (DUTCH PART)",
        "203":"SLOVAKIA (SLOVAK REPUBLIC)",
        "204":"SLOVENIA",
        "205":"SOLOMON ISLANDS",
        "206":"SOMALIA",
        "207":"SOUTH AFRICA",
        "208":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
        "209":"SOUTH KOREA",
        "210":"SOUTH SUDAN",
        "211":"SPAIN",
        "212":"SRI LANKA",
        "213":"SUDAN",
        "214":"SURINAME",
        "215":"SVALBARD & JAN MAYEN ISLANDS",
        "216":"SWAZILAND",
        "217":"SWEDEN",
        "218":"SWITZERLAND",
        "219":"SYRIAN ARAB REPUBLIC",
        "220":"TAIWAN",
        "221":"TAJIKISTAN",
        "222":"TANZANIA",
        "223":"THAILAND",
        "224":"TIMOR-LESTE",
        "225":"TOGO",
        "226":"TOKELAU",
        "227":"TONGA",
        "228":"TRINIDAD AND TOBAGO",
        "229":"TUNISIA",
        "230":"TURKEY",
        "231":"TURKMENISTAN",
        "232":"TURKS AND CAICOS ISLANDS",
        "233":"TUVALU",
        "234":"UGANDA",
        "235":"UKRAINE",
        "236":"UNITED ARAB EMIRATES",
        "237":"UNITED KINGDOM",
        "238":"UNITED STATES MINOR OUTLYING ISLANDS",
        "239":"U.S.A.",
        "240":"UNITED STATES VIRGIN ISLANDS",
        "241":"URUGUAY",
        "242":"UZBEKISTAN",
        "243":"VANUATU",
        "244":"VENEZUELA",
        "245":"VIETNAM",
        "246":"WALLIS AND FUTUNA",
        "247":"WESTERN SAHARA",
        "248":"YEMEN",
        "249":"ZAMBIA",
        "250":"ZIMBABWE",
        "251":"NETHERLANDS ANTILLES",
        "252":"OTHER"
        ]
}


